name: Build and release

on: [push]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Debug
        run: |
          echo ${GOPATH}
          echo ${GOROOT}
          echo ${GOCACHE}
          echo ${GOENV}
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: go/src/mama

      - name: Build
        run: |
          go get ./...
          go build ./...
        env:
          GOPATH: /home/runner/work/mama/mama/go
