name: Build and Release

on: [push]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Install Go
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: go/src/mama

      - name: Dependencies
        run: |
            go get ./...
        env:
          GOPATH: /home/runner/work/mama/mama/go
      
      - name: Create Release Directories
        run: |
            mkdir release-template
            cd go/src/mama
            cp configuration.ini LICENSE server.crt server.key README.md ../../../release-template/
            cd ../../..
            mkdir release
            cp -r release-template release/linux-386
            cp -r release-template release/linux-amd64
            cp -r release-template release/windows-386
            cp -r release-template release/windows-amd64
            
        env:
          GOPATH: /home/runner/work/mama/mama/go

      - name: Build Executables
        run: |
          GOOS=linux GOARCH=386 go build -o ./release/linux-386/monitoring-agent ./go/src/mama/main.go
          GOOS=linux GOARCH=amd64 go build -o ./release/linux-amd64/monitoring-agent ./go/src/mama/main.go
          GOOS=windows GOARCH=386 go build -o ./release/windows-386/monitoring-agent.exe ./go/src/mama/main.go
          GOOS=windows GOARCH=amd64 go build -o ./release/windows-amd64/monitoring-agent.exe ./go/src/mama/main.go
        env:
          GOPATH: /home/runner/work/mama/mama/go
      
      - name: Create release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "build-${{ steps.current-time.outputs.time }}-${{ steps.short-sha.outputs.sha }}"
          tag: "build-${{ steps.short-sha.outputs.sha }}"
          draft: true
          prerelease: true
          gzip: folders
          files: >
            release/*
          
      - uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
