name: Build and Release

on: [push]

jobs:
  build-release:

    runs-on: ubuntu-latest

    env:
        GOPATH: ${{ github.workspace }}/go
        SRCPATH: ${{ github.workspace }}/go/src/mama

    steps:
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Install Go
        uses: actions/setup-go@v2
            go-version: 1.16.x
            
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRCPATH }}

      - name: Dependencies & Build
        run: |
          for os in {linux,windows,freebsd}; do 
            for arch in {386,amd64}; do 
              echo "Building $os-$arch"
              
              suffix=$([ "$os" == "windows" ] && echo ".exe" || echo "")

              mkdir -p ./release/$os-$arch
              cp ${{ env.SRCPATH }}/installService.cmd ${{ env.SRCPATH }}/configuration.ini ${{ env.SRCPATH }}/LICENSE ${{ env.SRCPATH }}/server.crt ${{ env.SRCPATH }}/server.key ${{ env.SRCPATH }}/README.md ./release/$os-$arch

              GOOS=$os GOARCH=$arch go get ./...
              GOOS=$os GOARCH=$arch go build -o ./release/$os-$arch/monitoring-agent$suffix ${{ env.SRCPATH }}

            done
          done
          

      - name: Create release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "build-${{ steps.current-time.outputs.time }}-${{ steps.short-sha.outputs.sha }}"
          tag: "build-${{ steps.short-sha.outputs.sha }}"
          draft: true
          prerelease: true
          gzip: folders
          files: >
            release/*
          
      - uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
