name: Build and release

on: [push]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      
      - name: Debug
        run: |
          echo ${GOPATH}
          echo ${GOROOT}
          echo ${GOCACHE}
          echo ${GOENV}
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: go/src/mama

      - name: Dependencies
        run: go get ./...
        env:
          GOPATH: /home/runner/work/mama/mama/go

      - name: Build Executables
        run: |
          GOOS=linux GOARCH=386 go build -o ./linux-386 ./go/src/mama/cmd/mamasrv/mamasrv.go
          GOOS=linux GOARCH=amd64 go build -o ./linux-amd64 ./go/src/mama/cmd/mamasrv/mamasrv.go
          GOOS=windows GOARCH=386 go build -o ./windows-386.exe ./go/src/mama/cmd/mamasrv/mamasrv.go
          GOOS=windows GOARCH=amd64 go build -o ./windows-amd64.exe ./go/src/mama/cmd/mamasrv/mamasrv.go
        env:
          GOPATH: /home/runner/work/mama/mama/go
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-*-*
      
