name: Build and release

on: [push]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Debug
        run: |
          echo ${GOPATH}
          echo ${GOROOT}
          echo ${GOCACHE}
          echo ${GOENV}
      
      - name: Build
        run: go build -o release
