name: Build and release

on: [push]

jobs:

  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          pwd
          echo GOPATH: ${GOPATH}
          echo GOROOT: ${GOROOT}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: go/src/mama
      
      - name: Make Binaries
        uses: izumin5210/action-go-crossbuild@v1
        with:
          package: ./cmd/mamasrv
        
        env:
          GOPATH: /home/runner/work/mama/mama/go
      
