on: [push, pull_request]
name: Test

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
        GOPATH: ${{ github.workspace }}/go
        SRCPATH: ${{ github.workspace }}/go/src/mama

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{env.SRCPATH}}/

      - name: Dependencies
        run: |
            go get ./...

      - name: Test
        run: |
          go test -cover ${{env.SRCPATH}}/...