on: [push, pull_request]
name: Test

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: go/src/infraweavers/mama
      - name: Test
        run: |
          go get github.com/gorilla/mux
          go test -cover $(go list ./...)
        env:
          GOPATH: /home/runner/work/mama/mama/go