name: zztest

on: [workflow_dispatch]

jobs:

  build-release:
    runs-on: windows-latest
    env:
        SRCPATH: ${{ github.workspace }}/go/src/mama

    steps:
        
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
          
      - name: Install WIX Tool Set
        run: |
          Invoke-WebRequest -UseBasicParsing -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
          & ".\wix311.exe" "/q"
            
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRCPATH }}

      - name: Dependencies & Build
        run: |
          $os="windows"
          $arch="amd64"
          $goversion="1.16.x"
          Write-Host "Building $os-$arch-$goversion"
          
          New-Item -Type Directory ./release/$os-$arch-$goversion
          
          Set-Location -Path ${{ env.SRCPATH }}
          
          $env:GO111MODULE="on" 
          $env:GOOS="$os"
          $env:GOARCH=$arch
          go get ./...
          go build -o ${{ env.SRCPATH }}/monitoring-agent.exe
          
      - name: Create MSI Installer
        run: |
          $os="windows"
          $arch="amd64"
          $goversion="1.16.x"
          Write-Host "Building MSI Installer For $os-$arch-$goversion"
          
          Push-Location -Path ${{ env.SRCPATH }}
          & "c:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" "./monitoring-agent.wxs"
          & "c:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" "./monitoring-agent.wixobj"
          Pop-Location
          Copy-Item -Path ${{ env.SRCPATH }}/monitoring-agent.msi -Destination ./release/$os-$arch-$goversion/monitoring-agent-amd64-1.16-${{ steps.short-sha.outputs.sha }}.msi

      - name: upload MSI
        uses: actions/upload-artifact@v2
        with:
          name: "windows-amd64-1.16.x-${{ steps.short-sha.outputs.sha }}"
          path: release/
