name: zztest

on: [workflow_dispatch]

jobs:

  build-release:
    runs-on: windows-latest
    env:
        SRCPATH: ${{ github.workspace }}/go/src/mama

    steps:
        
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
          
      - name: Install WIX Tool Set
        run: |
          Invoke-WebRequest -UseBasicParsing -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
          & "C:\Users\danielcadden\Downloads\wix311.exe" "/q"
            
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRCPATH }}

      - name: Dependencies & Build
        run: |
          $os="windows"
          $arch="amd64"
          $goversion="1.16.x"
          Write-Host "Building $os-$arch-$goversion"
          
          $suffix=".exe"
          New-Item -Type Directory ./release/$os-$arch-$goversion
          @( 
            "${{ env.SRCPATH }}/installService.cmd",
            "${{ env.SRCPATH }}/uninstallService.cmd",
            "${{ env.SRCPATH }}/configuration.ini",
            "${{ env.SRCPATH }}/LICENSE",
            "${{ env.SRCPATH }}/server.crt",
            "${{ env.SRCPATH }}/server.key",
            "${{ env.SRCPATH }}/README.md",
            "${{ env.SRCPATH }}/cacert.pem"
          ) | ForEach-Object { Copy-Item -Path $_ -Destination  .\release\$os-$arch-$goversion }
          
          Push-Location -Path ${{ env.SRCPATH }}
          
          $env:GO111MODULE="on" 
          $env:GOOS="$os"
          $env:GOARCH=$arch
          go get ./...
          go build -o ${{ env.SRCPATH }}/monitoring-agent$suffix
          Pop-Location
          Copy-Item -Path ${{ env.SRCPATH }}/monitoring-agent$suffix -Destination ./release/$os-$arch-$goversion/monitoring-agent$suffix
