name: zztest

on: [push]

jobs:

  build-release:
    runs-on: ubuntu-latest
    env:
        SRCPATH: ${{ github.workspace }}/go/src/mama

    steps:
        
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
            
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRCPATH }}

      - name: Dependencies & Build
        run: |
          os=linux
          arch=amd64
          goversion=1.16
          echo "Building $os-$arch-$goversion"
          
          suffix=$([ "$os" == "windows" ] && echo ".exe" || echo "")
          mkdir -p ./release/$os-$arch-$goversion
          cp ${{ env.SRCPATH }}/installService.cmd ${{ env.SRCPATH }}/uninstallService.cmd ${{ env.SRCPATH }}/configuration.ini ${{ env.SRCPATH }}/LICENSE ${{ env.SRCPATH }}/server.crt ${{ env.SRCPATH }}/server.key ${{ env.SRCPATH }}/README.md ${{ env.SRCPATH }}/cacert.pem ./release/$os-$arch-$goversion
          
          pushd ${{ env.SRCPATH }}
          
          GO111MODULE=on GOOS=$os GOARCH=$arch go get ./...
          GO111MODULE=on GOOS=$os GOARCH=$arch go build -o ${{ env.SRCPATH }}/monitoring-agent$suffix
          popd
          cp ${{ env.SRCPATH }}/monitoring-agent$suffix ./release/$os-$arch-$goversion/monitoring-agent$suffix
          
      - name: Create Deb
        run: |
          cd ${{ env.SRCPATH }}/..
          dpkg-deb --build ${{ env.SRCPATH }}
          ls ${{ env.SRCPATH }}
          
      - name: upload package
        uses: actions/upload-artifact@v2
        with:
          name: "debian-ubuntu-amd64-1.16.x-${{ steps.short-sha.outputs.sha }}.deb"
          path: ${{ env.SRCPATH }}/*.deb
